[2023-10-07T08:43:45.796+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: networkrail_movements_to_gcs_and_then_bigquery.load_data_from_gcs_to_bigquery backfill__2023-09-10T02:00:00+00:00 [queued]>
[2023-10-07T08:43:45.817+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: networkrail_movements_to_gcs_and_then_bigquery.load_data_from_gcs_to_bigquery backfill__2023-09-10T02:00:00+00:00 [queued]>
[2023-10-07T08:43:45.823+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-07T08:43:45.857+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_from_gcs_to_bigquery> on 2023-09-10 02:00:00+00:00
[2023-10-07T08:43:45.862+0000] {standard_task_runner.py:57} INFO - Started process 3888 to run task
[2023-10-07T08:43:45.866+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'networkrail_movements_to_gcs_and_then_bigquery', 'load_data_from_gcs_to_bigquery', 'backfill__2023-09-10T02:00:00+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/networkrail_movements_to_gcs_and_then_bigquery.py', '--cfg-path', '/tmp/tmp03ktdz8x']
[2023-10-07T08:43:45.867+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask load_data_from_gcs_to_bigquery
[2023-10-07T08:43:45.950+0000] {task_command.py:415} INFO - Running <TaskInstance: networkrail_movements_to_gcs_and_then_bigquery.load_data_from_gcs_to_bigquery backfill__2023-09-10T02:00:00+00:00 [running]> on host 6b4be57cca48
[2023-10-07T08:43:46.071+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Skooldio' AIRFLOW_CTX_DAG_ID='networkrail_movements_to_gcs_and_then_bigquery' AIRFLOW_CTX_TASK_ID='load_data_from_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2023-09-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2023-09-10T02:00:00+00:00'
[2023-10-07T08:43:47.406+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/networkrail_movements_to_gcs_and_then_bigquery.py", line 192, in _load_data_from_gcs_to_bigquery
    job.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Too many values in row starting at position: 153916. Found 54 column(s) while expected 29. File: gs://deb2-bootcamp005/networkrail/movements/2023-09-10/movements.csv
[2023-10-07T08:43:47.420+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=networkrail_movements_to_gcs_and_then_bigquery, task_id=load_data_from_gcs_to_bigquery, execution_date=20230910T020000, start_date=20231007T084345, end_date=20231007T084347
[2023-10-07T08:43:47.440+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task load_data_from_gcs_to_bigquery (400 Error while reading data, error message: Too many values in row starting at position: 153916. Found 54 column(s) while expected 29. File: gs://deb2-bootcamp005/networkrail/movements/2023-09-10/movements.csv; 3888)
[2023-10-07T08:43:47.485+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-07T08:43:47.502+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
